Update boinc_init
- Made log appended (note, may fill drive, make a log rotate package)
- Made a "drain" option for when I am about to kill a server, so I don't waste work units
- Cleaned up some text

diff --git a/boinc_init b/boinc_init
--- a/boinc_init
+++ b/boinc_init
@@ -8,11 +8,15 @@ BOINC_PATH="/opt/BOINC"
 boinc_start() {
     if [ -x /opt/BOINC/run_client ]; then
         echo "Starting BOINC..."
-        $BOINC_PATH/run_client > $BOINC_LOG &
+        ${BOINC_PATH}/run_client >> ${BOINC_LOG} &
+    else
+        echo "FAIL: cannot find ${BOINC_PATH}/run_client. Exiting." | tee -a ${BOINC_LOG}
+        exit 1
     fi
 }
 boinc_stop() {
     echo "Stopping BOINC..."
+    echo "Boinc stopped manually by user $0" >> ${BOINC_LOG}
     sudo killall boinc
 }
 boinc_restart() {
@@ -21,19 +25,26 @@ boinc_restart() {
     boinc_start
 }
 case "$1" in
-  'start')
+    'start')
           boinc_start
           ;;
-  'stop')
+    'stop')
           boinc_stop
           ;;
-'restart')
+    'restart')
           boinc_restart
           ;;
-'attach')
-        $BOINC_PATH/boinc -no_gui_rpc -attach_project http://setiathome.berkeley.edu d14af2375aa9c85dd1251f0f04d09654 > $BOINC_LOG &
+    'attach')
+        ${BOINC_PATH}/boinc -no_gui_rpc -attach_project http://setiathome.berkeley.edu d14af2375aa9c85dd1251f0f04d09654 > ${BOINC_LOG} &
         echo "Starting BOINC with Grig's account attached (first run)..."
           ;;
-        *)
-          echo "$0 start|stop|restart|attach" 
+    'drain')
+        boinc_stop
+        sleep 3
+        echo "Starting BOINC but will exit when all work units are complete..."
+        echo "BOINC restarted with exit_when_idle mode.  Will exit upon completion of work units." | tee -a ${BOINC_LOG}
+        ${BOINC_PATH}/run_client --exit_when_idle >> ${BOINC_LOG}
+          ;;
+    *)
+          echo "$0 start|stop|restart|attach|drain" 
 esac
